// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuQDq0aZygdTUvwbfCCpzRJeq8OzIfT9k',
    appId: '1:37911985738:web:aab946b557c1bda45670b3',
    messagingSenderId: '37911985738',
    projectId: 'snapsync-ai-1ee70',
    authDomain: 'snapsync-ai-1ee70.firebaseapp.com',
    storageBucket: 'snapsync-ai-1ee70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbIvWdSylwTkpMoooaQle4XxqWi290TTs',
    appId: '1:37911985738:android:e93517ebb8b3788d5670b3',
    messagingSenderId: '37911985738',
    projectId: 'snapsync-ai-1ee70',
    storageBucket: 'snapsync-ai-1ee70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGwaR1At88QYD3xrri1vm7PGFAFz0gugg',
    appId: '1:37911985738:ios:7311854f456d9cef5670b3',
    messagingSenderId: '37911985738',
    projectId: 'snapsync-ai-1ee70',
    storageBucket: 'snapsync-ai-1ee70.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGwaR1At88QYD3xrri1vm7PGFAFz0gugg',
    appId: '1:37911985738:ios:7311854f456d9cef5670b3',
    messagingSenderId: '37911985738',
    projectId: 'snapsync-ai-1ee70',
    storageBucket: 'snapsync-ai-1ee70.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuQDq0aZygdTUvwbfCCpzRJeq8OzIfT9k',
    appId: '1:37911985738:web:696f2ccecfdcdba15670b3',
    messagingSenderId: '37911985738',
    projectId: 'snapsync-ai-1ee70',
    authDomain: 'snapsync-ai-1ee70.firebaseapp.com',
    storageBucket: 'snapsync-ai-1ee70.firebasestorage.app',
  );
}
